# Print welcome message
print("Welcome to TicTacToe!")
# Get char
char = input("Would you like to be \'X\' or \'O\'?")
# Check if char is 'X' or 'O'
def board(a,b):
    print('   |   |')
    print(' ' + board[1,7] + ' | ' + board[1,8] + ' | ' + board[1,9])
    print('   |   |')
    print('-----------')
    print('   |   |')
    print(' ' + board[1,4] + ' | ' + board[1,5] + ' | ' + board[1,6])
    print('   |   |')
    print('-----------')
    print('   |   |')
    print(' ' + board[1,1] + ' | ' + board[1,2] + ' | ' + board[1,3])
    print('   |   |')
    print('         ')#create space between the boards
    print('   |   |')
    print(' ' + board[2,7] + ' | ' + board[2,8] + ' | ' + board[2,9])
    print('   |   |')
    print('-----------')
    print('   |   |')
    print(' ' + board[2,4] + ' | ' + board[2,5] + ' | ' + board[2,6])
    print('   |   |')
    print('-----------')
    print('   |   |')
    print(' ' + board[2,1] + ' | ' + board[2,2] + ' | ' + board[2,3])
    print('   |   |')
    print('         ')#create space
    print('   |   |')
    print(' ' + board[3,7] + ' | ' + board[3,8] + ' | ' + board[3,9])
    print('   |   |')
    print('-----------')
    print('   |   |')
    print(' ' + board[3,4] + ' | ' + board[3,5] + ' | ' + board[3,6])
    print('   |   |')
    print('-----------')
    print('   |   |')
    print(' ' + board[3,1] + ' | ' + board[3,2] + ' | ' + board[3,3])
    print('   |   |')
