# Print welcome message
print("Welcome to TicTacToe!")
# Get char
char = input("Would you like to be \'X\' or \'O\'?")
# Check if char is 'X' or 'O'
def drawBoard(a):
    print('   |   |')
    print(' ' + drawBoard[17] + ' | ' + drawBoard[18] + ' | ' + drawBoard[19])
    print('   |   |')
    print('-----------')
    print('   |   |')
    print(' ' + drawBoard[14] + ' | ' + drawBoard[15] + ' | ' + drawBoard[16])
    print('   |   |')
    print('-----------')
    print('   |   |')
    print(' ' + drawBoard[11] + ' | ' + drawBoard[12] + ' | ' + drawBoard[13])
    print('   |   |')
    print('         ')#create space between the boards
    print('   |   |')
    print(' ' + drawBoard[27] + ' | ' + drawBoard[28] + ' | ' + drawBoard[29])
    print('   |   |')
    print('-----------')
    print('   |   |')
    print(' ' + drawBoard[24] + ' | ' + drawBoard[25] + ' | ' + drawBoard[26])
    print('   |   |')
    print('-----------')
    print('   |   |')
    print(' ' + drawBoard[21] + ' | ' + drawBoard[22] + ' | ' + drawBoard[23])
    print('   |   |')
    print('         ')#create space
    print('   |   |')
    print(' ' + drawBoard[37] + ' | ' + drawBoard[38] + ' | ' + drawBoard[39])
    print('   |   |')
    print('-----------')
    print('   |   |')
    print(' ' + drawBoard[34] + ' | ' + drawBoard[35] + ' | ' + drawBoard[36])
    print('   |   |')
    print('-----------')
    print('   |   |')
    print(' ' + drawBoard[31] + ' | ' + drawBoard[32] + ' | ' + drawBoard[33])
    print('   |   |')
print(drawBoard(12))
input()

