# Print welcome message
print("Welcome to TicTacToe!")
# Get char
char = input("Would you like to be \'X\' or \'O\'?")
# Check if char is 'X' or 'O'

board = range(0, 40)

def drawinstructionBoard(a):
    print('    |    |')
    print(' ' + str(board[17]) + ' | ' + str(board[18]) + ' | ' + str(board[19]))
    print('    |    |')
    print('--------------')
    print('    |    |')
    print(' ' + str(board[14]) + ' | ' + str(board[15]) + ' | ' + str(board[16]))
    print('    |    |')
    print('--------------')
    print('    |    |')
    print(' ' + str(board[11]) + ' | ' + str(board[12]) + ' | ' + str(board[13]))
    print('    |    |')
    print(' ')
    print('    |    |')
    print(' ' + str(board[27]) + ' | ' + str(board[28]) + ' | ' + str(board[29]))
    print('    |    |')
    print('--------------')
    print('    |    |')
    print(' ' + str(board[24]) + ' | ' + str(board[25]) + ' | ' + str(board[26]))
    print('    |    |')
    print('--------------')
    print('    |    |')
    print(' ' + str(board[21]) + ' | ' + str(board[22]) + ' | ' + str(board[23]))
    print('    |    |')
    print(' ')
    print('    |    |')
    print(' ' + str(board[37]) + ' | ' + str(board[38]) + ' | ' + str(board[39]))
    print('    |    |')
    print('--------------')
    print('    |    |')
    print(' ' + str(board[34]) + ' | ' + str(board[35]) + ' | ' + str(board[36]))
    print('    |    |')
    print('--------------')
    print('    |    |')
    print(' ' + str(board[31]) + ' | ' + str(board[32]) + ' | ' + str(board[33]))
    print('    |    |')
a=input("Do you want instructions?")
if a=="YES":
    drawinstructionBoard(17)
def drawBoard():
    print('   |   |')
    print(' ' + board[17] + ' | ' + board[18] + ' | ' + board[19])
    print('   |   |')
    print('-----------')
    print('   |   |')
    print(' ' + board[14] + ' | ' + board[15] + ' | ' + board[16])
    print('   |   |')
    print('-----------')
    print('   |   |')
    print(' ' + board[11] + ' | ' + board[12] + ' | ' + board[13])
    print('   |   |')
    print(' ')
    print('   |   |')
    print(' ' + board[27] + ' | ' + board[28] + ' | ' + board[29])
    print('   |   |')
    print('-----------')
    print('   |   |')
    print(' ' + board[24] + ' | ' + board[25] + ' | ' + board[26])
    print('   |   |')
    print('-----------')
    print('   |   |')
    print(' ' + board[21] + ' | ' + board[22] + ' | ' + board[23])
    print('   |   |')
    print(' ')
    print('   |   |')
    print(' ' + board[37] + ' | ' + board[38] + ' | ' + board[39])
    print('   |   |')
    print('-----------')
    print('   |   |')
    print(' ' + board[34] + ' | ' + board[35] + ' | ' + board[36])
    print('   |   |')
    print('-----------')
    print('   |   |')
    print(' ' + board[31] + ' | ' + board[32] + ' | ' + board[33])
    print('   |   |')
if a=="NO":
     drawBoard()
input()
